version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
      - "8000:8000"
    depends_on:
      - mysql
    links:
      - mysql
      - mailhog
    networks:
      - ecomm

  mysql:
    image: mariadb:11
    networks:
      - ecomm
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerce

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - ecomm


networks:
  ecomm:

